meta:
  environment: (( merge ))
  dns_root: (( merge ))
  security_groups: (( merge ))
  persistent_disk: 4096

  stemcell:
    name: bosh-aws-xen-centos-7-go_agent
    version: latest

jobs:
  - name: appfirst
    instances: 1
    networks:
      - name: appfirst
    persistent_disk: (( meta.persistent_disk ))
    properties:
      appfirst:
        tenant_id: "ID # GOES HERE"

compilation:
  cloud_properties:
    instance_type: m1.small

resource_pools:
  - name: small_z1
    cloud_properties:
      instance_type: m1.small

networks:
  - name: floating
    type: vip
    cloud_properties: {}
  - name: appfirst
    type: dynamic
    cloud_properties:
      security_groups: (( meta.security_groups ))
